language: ruby
dist: xenial
sudo: false
rvm:
- 2.3.8

addons:
  apt:
    packages:
    - chromium-browser

before_install:
  # Rails 4.x requires bundler version < 2.0.
  - >
    if [[ $BUNDLE_GEMFILE == "${PWD}/spec/gemfiles/rails_4_2.gemfile" ]]; then
      "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
      gem install bundler --version='~> 1.17'
      bundler --version
    fi

cache:
  bundler: true
  directories:
  # Cache the Onebox data and views to speed up tests
  - tmp/cache/onebox-data
  - tmp/cache/onebox-views
  - spec/dummy/tmp/cache/onebox-data
  - spec/dummy/tmp/cache/onebox-views

bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile
  - spec/gemfiles/rails_5_1.gemfile
  - spec/gemfiles/rails_5_2.gemfile
env:
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3
  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
  global:
  - COVERAGE=1
  - TRAVIS=1
services:
- postgresql
- mysql

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- SIMPLECOV_NAME="test:nojs" bundle exec rspec --force-color --format d --tag=~js
- SIMPLECOV_NAME="test:js" bundle exec rspec --force-color --format d --tag=js
- bundle exec rubocop
- MIGRATION_SPEC=1 SIMPLECOV_NAME="test:migrations" bundle exec rspec spec/migration --force-color --format d
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: bnoj7Q/2yA3gtJ2IR/YtXrWCGvN7ukHKnhg1oNYJsOYNk0oEMMgjmGnIRrcdxO4peyOid6aKlcMmP7zrOzPEJsN3qAA4UUCRGq0TgZ2RDMX1sRZ8NN/xCyt84WU9aEtTF0V1hUyG/OaQ7G65XN/XuwJGzw6VDSZE54FSdR/5/eQ=
