db:
  image: onjin/alpine-postgres:9.6
  ports:
    - "5434:5432"
  environment:
    POSTGRES_USER: root
web:
  build: .
  volumes:
    - ./Rakefile:/thredded/Rakefile
    - ./config.ru:/thredded/config.ru
    - ./app:/thredded/app
    - ./bin:/thredded/bin
    - ./config:/thredded/config
    - ./db:/thredded/db
    - ./lib:/thredded/lib
    - ./script:/thredded/script
    - ./spec:/thredded/spec
    - ./vendor:/thredded/vendor
    # Ignore these paths
    - /thredded/spec/dummy/tmp/
  working_dir: /thredded
  environment:
    DB: postgresql
    DB_USERNAME: root
    DB_PASSWORD:
  command: >
    bash -c 'script/wait-for-tcp $$DB_1_PORT_5432_TCP_ADDR $$DB_1_PORT_5432_TCP_PORT &&
             bundle exec rake db:drop db:create db:migrate &&
             bundle exec rake db:seed &&
             bundle exec rake dev:server'
  ports:
    - "9292:9292"
  links:
    - db
