defaults: &defaults
  host: localhost
  adapter: <%= ENV['DB'] || 'postgresql' %>
  encoding: utf8
  min_messages: WARNING
  pool: 10
  reaping_frequency: 5

development:
  <<: *defaults
  host: localhost
  database: thredded_gem_dev

test:
  <<: *defaults
  host: localhost
  database: thredded_gem_test
