defaults: &defaults
  host: <%= ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_PORT', 5432) %>
  adapter: <%= ENV['DB'] || 'postgresql' %>
  encoding: utf8
  min_messages: WARNING

development:
  <<: *defaults
  database: thredded_gem_dev

test:
  <<: *defaults
  database: thredded_gem_test
